server:
  applicationConnectors:
    - type: http
      port: 9000
  adminConnectors:
    - type: http
      port: 9001

credentials:
  login: admin
  password: admin

tagService:
  connector:
    type: http
    address: localhost
    port: 8080
  login: adminSzefo
  password: peja997

jobIntervals:
  birthdayJob: 50
  zodiacJob: 60